title: "[Your Name]"
description: "PhD student in [Field] at [Institution]. ML/HPC systems and privacy-preserving data."
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
minima:
  social_links:
    - { platform: github,  user_url: "https://github.com/yourusername" }
    - { platform: linkedin, user_url: "https://www.linkedin.com/in/yourusername/" }
    - { platform: scholar,  user_url: "https://scholar.google.com/citations?user=YOUR_ID" }

# Optional: enable kramdown extras (TOC, footnotes, math)
markdown: kramdown
kramdown:
  input: GFM
  math_engine: mathjax
